name: easy_dev_toolkit
description: A comprehensive Flutter toolkit with responsive sizing, adaptive widgets, networking, and storage utilities.
version: 0.1.2
homepage: https://github.com/ajutheman/easy_dev_toolkit
repository: https://github.com/ajutheman/easy_dev_toolkit
issue_tracker: https://github.com/ajutheman/easy_dev_toolkit/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^7.0.0
  fluttertoast: ^9.0.0
  dio: ^5.7.0
  shared_preferences: ^2.5.4
  path_provider: ^2.1.5
  encrypt: ^5.0.3
  google_fonts: ^6.3.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
