name: easy_dev_toolkit
description: A mixed Material/iOS clean UI toolkit with responsive sizing, adaptive widgets, network helpers, layout utilities, and reusable components â€” designed to speed up Flutter development.
version: 0.1.1
homepage: https://github.com/ajmalm/easy_dev_toolkit
repository: https://github.com/ajmalm/easy_dev_toolkit
issue_tracker: https://github.com/ajmalm/easy_dev_toolkit/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^6.1.5
  fluttertoast: ^9.0.0
  dio: ^5.7.0
  shared_preferences: ^2.3.3
  path_provider: ^2.0.0
  encrypt: ^5.0.1
  google_fonts: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
